apiVersion: v1
kind: Service
metadata: 
   name: myappdemo-svc
   labels: 
      app: myappdemo
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
  selector: 
      app: myappdemo