apiVersion: apps/v1
kind: Deployment
metadata: 
     name: myappdemo-deploy
     labels: 
       app: myappdemo
spec: 
    replicas: 1
    selector:
      matchLabels:
        app: myappdemo
    template:
        metadata: 
           name: myappdemo
           labels: 
             app: myappdemo
        spec:   
         containers:
          - image: vsiraparapu/mydemoapp:latest
            name:  myappdemo
          
          